### ISSUE TITLE
[Important] Map Design

### ISSUE THREAD

**Issue by emiliobool** [horchatas/ggj2015#7]
we need to get a csv and tilset to import to the game, also a list of collision tiles

**Comment by sodapopjam** [comment]
?

**Comment by sodapopjam** [comment]
I think this should be reopened

**Comment by sodapopjam** [comment]
Not yet?

**Comment by emiliobool** [comment]
trying again

**Comment by emiliobool** [comment]
closing, should appear on slack

**Comment by sodapopjam** [comment]
did it appear?
