### ISSUE TITLE
Credits Images

### ISSUE THREAD

**Issue by emiliobool** [horchatas/ggj2015#8]

**Comment by emiliobool** [comment]
grandmas house first?

**Comment by sodapopjam** [comment]
![1](https://cloud.githubusercontent.com/assets/10158271/5893106/4fcda6ee-a495-11e4-931c-22474b3197f2.png)
![2](https://cloud.githubusercontent.com/assets/10158271/5893107/4fddd3e8-a495-11e4-8a22-8bfee57f6349.png)
![3](https://cloud.githubusercontent.com/assets/10158271/5893108/4fddea72-a495-11e4-9e33-dc18a199d3f0.png)
![Uploading 4.png . . .]()
![Uploading 5.png . . .]()
![Uploading 2015-01-24 12_13_32-Facebook.png . . .]()
![Uploading 2015-01-24 18_57_16-Under The Rain.png . . .]()

**Comment by sodapopjam** [comment]
![6](https://cloud.githubusercontent.com/assets/10158271/5893140/02d8b5f8-a496-11e4-88e2-93c47e72fe1f.png)

**Comment by emiliobool** [comment]
working on this
